### PR TITLE
Add Openalea as a submodule

### PR DESCRIPTION
**Pull request by pradal**
Build core and vpltk

### CODE REVIEW

**Comment by pradal** [comment]
@artzet-s You can merge. I have explicitly stop the appveyor build do to config errors.

**Comment by artzet-s** [comment]
Great Job ! 

You can also remove the recipe directory of :
openalea.visualea
openalea.oalab
openalea.grapheditor

**Comment by pradal** [comment]
Sure. Done.

**Comment by artzet-s** [comment]
Ok great !  In accordance to the previous successful continuous integration test and files modified with this last commit, the result should be not change. So I merge.

**Pull request merged**
